// export const norwegianWords = [
// 	{ word: "forståelse", hint: "Evnen til å oppfatte og tolke informasjon." },
// 	{ word: "utvikling", hint: "En prosess der noe blir bedre eller mer avansert." },
// 	{ word: "bevissthet", hint: "Tilstand av å være klar over noe eller seg selv." },
// 	{ word: "selvstendig", hint: "En person som klarer seg uten hjelp fra andre." },
// 	{ word: "anerkjennelse", hint: "Når noen får ros eller blir lagt merke til for noe bra." },
// 	{ word: "tilgjengelig", hint: "Noe som er lett å få tak i eller bruke." },
// 	{ word: "forpliktelse", hint: "En avtale eller ansvar man må følge opp." },
// 	{ word: "gjennomføre", hint: "Å gjøre ferdig en oppgave eller plan." },
// 	{ word: "sannsynlighet", hint: "Hvor stor sjanse det er for at noe skjer." },
// 	{ word: "overbevisende", hint: "Noe som får andre til å tro på det du sier." },
// 	{ word: "forutsigelse", hint: "En antakelse om hva som vil skje i fremtiden." },
// 	{ word: "hensiktsmessig", hint: "Noe som passer godt til formålet." },
// 	{ word: "innflytelse", hint: "Evnen til å påvirke andre eller en situasjon." },
// 	{ word: "oppmerksomhet", hint: "Når man konsentrerer seg om noe eller noen." },
// 	{ word: "tilrettelegge", hint: "Å gjøre det lettere for andre å få til noe." },
// 	{ word: "virkeligheten", hint: "Det som faktisk skjer, ikke fantasi." },
// 	{ word: "forventninger", hint: "Tanker om hva som kommer til å skje." },
// 	{ word: "selvrefleksjon", hint: "Å tenke over egne tanker og handlinger." },
// 	{ word: "utfordringer", hint: "Noe som er vanskelig og krever innsats å løse." },
// 	{ word: "bærekraftig", hint: "Noe som varer lenge uten å skade miljøet." },
// 	{ word: "kompetanse", hint: "Kunnskap og ferdigheter innen et område." },
// 	{ word: "kommunikasjon", hint: "Å utveksle informasjon mellom mennesker." },
// 	{ word: "samarbeid", hint: "Når flere personer jobber sammen mot et mål." },
// 	{ word: "kreativitet", hint: "Evnen til å skape noe nytt og originalt." },
// 	{ word: "inspirasjon", hint: "Følelse som motiverer til handling eller skapelse." },
// 	{ word: "toleranse", hint: "Å akseptere andres meninger og forskjellighet." },
// 	{ word: "empati", hint: "Evnen til å forstå andres følelser." },
// 	{ word: "respekt", hint: "Å vise høflighet og anerkjennelse overfor andre." },
// 	{ word: "integritet", hint: "Å være ærlig og handle i tråd med sine verdier." },
// 	{ word: "fleksibilitet", hint: "Evnen til å tilpasse seg endringer." },
// 	{ word: "engasjement", hint: "Å være interessert og aktiv i noe." },
// 	{ word: "dedikasjon", hint: "Å være fullt og helt forpliktet til noe." },
// 	{ word: "systematisk", hint: "Å gjøre ting på en organisert og planlagt måte." },
// 	{ word: "konstruktiv", hint: "Noe som bidrar positivt til forbedring." },
// 	{ word: "analytisk", hint: "Evnen til å bryte ned komplekse problemer." },
// 	{ word: "strategisk", hint: "Planlegging for å nå langsiktige mål." },
// 	{ word: "effektiv", hint: "Å oppnå gode resultater med minst mulig innsats." },
// 	{ word: "innovativ", hint: "Å innføre nye ideer eller metoder." },
// 	{ word: "målrettet", hint: "Å være fokusert på å nå bestemte mål." },
// 	{ word: "konsistent", hint: "Å være stabil og forutsigbar over tid." },
// 	{ word: "omfattende", hint: "Noe som inkluderer mange aspekter eller detaljer." },
// 	{ word: "grunnleggende", hint: "De viktigste og mest essensielle elementene." },
// 	{ word: "betydningsfull", hint: "Noe som har stor verdi eller viktighet." },
// 	{ word: "avgjørende", hint: "Noe som har stor innvirkning på utfallet." },
// 	{ word: "vesentlig", hint: "Noe som er viktig og nødvendig." },
// 	{ word: "relevant", hint: "Noe som er passende og har sammenheng med emnet." },
// 	{ word: "tilpasset", hint: "Noe som er endret for å passe bedre." },
// 	{ word: "forhåndsdefinert", hint: "Noe som er bestemt på forhånd." },
// 	{ word: "tilstrekkelig", hint: "Nok til å dekke behovet." },
// 	{ word: "nødvendig", hint: "Noe som må være til stede eller gjøres." },
// 	{ word: "anbefaling", hint: "Et forslag om hva som bør gjøres." },
// 	{ word: "betingelse", hint: "Et krav som må oppfylles." },
// 	{ word: "konsekvens", hint: "Resultatet av en handling eller beslutning." },
// 	{ word: "sammenheng", hint: "Forbindelse mellom forskjellige elementer." },
// 	{ word: "perspektiv", hint: "En måte å se på eller forstå noe." },
// 	{ word: "dimensjon", hint: "Et aspekt eller side ved noe." },
// 	{ word: "kapasitet", hint: "Maksimal mengde eller evne til å håndtere noe." },
// 	{ word: "potensial", hint: "Muligheter for fremtidig utvikling eller suksess." },
// 	{ word: "ressurser", hint: "Tilgjengelige midler eller materialer som kan brukes." },
// 	{ word: "struktur", hint: "Måten noe er organisert eller bygget opp." },
// 	{ word: "prosedyre", hint: "En bestemt måte å gjøre noe på." },
// 	{ word: "metodikk", hint: "Systematisk tilnærming til å løse problemer." },
// 	{ word: "tilnærming", hint: "En måte å håndtere eller nærme seg noe." },
// 	{ word: "implementering", hint: "Å sette en plan eller ide ut i praksis." },
// 	{ word: "evaluering", hint: "Prosessen med å vurdere kvalitet eller verdi." },
// 	{ word: "optimalisering", hint: "Å gjøre noe så bra som mulig." },
// 	{ word: "koordinering", hint: "Å organisere forskjellige aktiviteter sammen." },
// 	{ word: "prioritering", hint: "Å rangere oppgaver etter viktighet." },
// 	{ word: "planlegging", hint: "Å forberede og organisere fremtidige aktiviteter." },
// 	{ word: "dokumentasjon", hint: "Skriftlig materiale som beviser eller forklarer noe." },
// 	{ word: "informasjon", hint: "Data eller kunnskap som er kommunisert." },
// ];

export const norwegianWords = {
	easy: [
		// Basic everyday words
		{ word: "hus", hint: "Et sted hvor folk bor." },
		{ word: "bil", hint: "Et kjøretøy med fire hjul." },
		{ word: "mat", hint: "Det vi spiser for å overleve." },
		{ word: "vann", hint: "En klar væske vi trenger for å leve." },
		{ word: "bok", hint: "Noe vi leser med mange sider." },
		{ word: "skole", hint: "Et sted hvor barn lærer." },
		{ word: "familie", hint: "Foreldre, barn og andre nære slektninger." },
		{ word: "venn", hint: "En person du liker å være sammen med." },
		{ word: "arbeid", hint: "Det du gjør for å tjene penger." },
		{ word: "tid", hint: "Det som går fra fortid til fremtid." },
		{ word: "dag", hint: "24 timer fra morgen til kveld." },
		{ word: "natt", hint: "Den mørke tiden når folk sover." },
		{ word: "morgen", hint: "Første del av dagen." },
		{ word: "kveld", hint: "Siste del av dagen før natten." },
		{ word: "år", hint: "365 dager sammen." },
		{ word: "måned", hint: "Omtrent 30 dager sammen." },
		{ word: "uke", hint: "Syv dager sammen." },
		{ word: "penger", hint: "Det vi bruker for å kjøpe ting." },
		{ word: "butikk", hint: "Et sted hvor vi kjøper varer." },
		{ word: "kaffe", hint: "En varm, brun drikk mange liker om morgenen." },
		{ word: "brød", hint: "En hvit eller brun mat vi ofte spiser til frokost." },
		{ word: "smør", hint: "Gul fett som smøres på brød." },
		{ word: "melk", hint: "Hvit drikk som kommer fra kyr." },
		{ word: "kjøtt", hint: "Mat som kommer fra dyr." },
		{ word: "fisk", hint: "Dyr som lever i vannet og svømmer." },
		{ word: "grønnsaker", hint: "Sunne planter vi spiser, som gulrøtter og poteter." },
		{ word: "frukt", hint: "Søte ting som epler, bananer og appelsiner." },
		{ word: "klær", hint: "Det vi har på kroppen for ikke å fryse." },
		{ word: "sko", hint: "Det vi har på føttene når vi går ut." },
		{ word: "hår", hint: "Det som vokser på hodet vårt." },
		{ word: "øyne", hint: "Det vi ser med." },
		{ word: "ører", hint: "Det vi hører med." },
		{ word: "munn", hint: "Det vi spiser og snakker med." },
		{ word: "hender", hint: "Det på slutten av armene våre." },
		{ word: "føtter", hint: "Det vi går med." },
		{ word: "telefon", hint: "En ting vi ringer til andre med." },
		{ word: "dør", hint: "Det vi åpner og lukker for å gå inn og ut." },
		{ word: "vindu", hint: "Det vi ser gjennom i veggen." },
		{ word: "stol", hint: "Møbel vi sitter på." },
		{ word: "bord", hint: "Møbel vi spiser på eller jobber ved." },
		{ word: "seng", hint: "Møbel vi sover i." },
		{ word: "informasjon", hint: "Data eller kunnskap som er kommunisert." },
		{ word: "kommunikasjon", hint: "Å utveksle informasjon mellom mennesker." },
		{ word: "samarbeid", hint: "Når flere personer jobber sammen mot et mål." },
		{ word: "kreativitet", hint: "Evnen til å skape noe nytt og originalt." },
		{ word: "inspirasjon", hint: "Følelse som motiverer til handling eller skapelse." },
	],

	medium: [
		// Intermediate level words
		{ word: "forståelse", hint: "Evnen til å oppfatte og tolke informasjon." },
		{ word: "utvikling", hint: "En prosess der noe blir bedre eller mer avansert." },
		{ word: "selvstendig", hint: "En person som klarer seg uten hjelp fra andre." },
		{ word: "tilgjengelig", hint: "Noe som er lett å få tak i eller bruke." },
		{ word: "gjennomføre", hint: "Å gjøre ferdig en oppgave eller plan." },
		{ word: "sannsynlighet", hint: "Hvor stor sjanse det er for at noe skjer." },
		{ word: "overbevisende", hint: "Noe som får andre til å tro på det du sier." },
		{ word: "innflytelse", hint: "Evnen til å påvirke andre eller en situasjon." },
		{ word: "oppmerksomhet", hint: "Når man konsentrerer seg om noe eller noen." },
		{ word: "tilrettelegge", hint: "Å gjøre det lettere for andre å få til noe." },
		{ word: "virkeligheten", hint: "Det som faktisk skjer, ikke fantasi." },
		{ word: "forventninger", hint: "Tanker om hva som kommer til å skje." },
		{ word: "utfordringer", hint: "Noe som er vanskelig og krever innsats å løse." },
		{ word: "kompetanse", hint: "Kunnskap og ferdigheter innen et område." },
		{ word: "toleranse", hint: "Å akseptere andres meninger og forskjellighet." },
		{ word: "empati", hint: "Evnen til å forstå andres følelser." },
		{ word: "respekt", hint: "Å vise høflighet og anerkjennelse overfor andre." },
		{ word: "fleksibilitet", hint: "Evnen til å tilpasse seg endringer." },
		{ word: "engasjement", hint: "Å være interessert og aktiv i noe." },
		{ word: "effektiv", hint: "Å oppnå gode resultater med minst mulig innsats." },
		{ word: "målrettet", hint: "Å være fokusert på å nå bestemte mål." },
		{ word: "grunnleggende", hint: "De viktigste og mest essensielle elementene." },
		{ word: "avgjørende", hint: "Noe som har stor innvirkning på utfallet." },
		{ word: "relevant", hint: "Noe som er passende og har sammenheng med emnet." },
		{ word: "nødvendig", hint: "Noe som må være til stede eller gjøres." },
		{ word: "konsekvens", hint: "Resultatet av en handling eller beslutning." },
		{ word: "sammenheng", hint: "Forbindelse mellom forskjellige elementer." },
		{ word: "perspektiv", hint: "En måte å se på eller forstå noe." },
		{ word: "kapasitet", hint: "Maksimal mengde eller evne til å håndtere noe." },
		{ word: "potensial", hint: "Muligheter for fremtidig utvikling eller suksess." },
		{ word: "ressurser", hint: "Tilgjengelige midler eller materialer som kan brukes." },
		{ word: "struktur", hint: "Måten noe er organisert eller bygget opp." },
		{ word: "tilnærming", hint: "En måte å håndtere eller nærme seg noe." },
		{ word: "evaluering", hint: "Prosessen med å vurdere kvalitet eller verdi." },
		{ word: "koordinering", hint: "Å organisere forskjellige aktiviteter sammen." },
		{ word: "prioritering", hint: "Å rangere oppgaver etter viktighet." },
		{ word: "planlegging", hint: "Å forberede og organisere fremtidige aktiviteter." },
		{ word: "dokumentasjon", hint: "Skriftlig materiale som beviser eller forklarer noe." },
		// Additional medium words
		{ word: "erfaring", hint: "Kunnskap eller ferdigheter oppnådd gjennom praksis." },
		{ word: "trygghet", hint: "Følelse av å være beskyttet og sikker." },
		{ word: "mulighet", hint: "En sjanse eller anledning til å gjøre noe." },
		{ word: "kvalitet", hint: "Hvor god eller dårlig noe er." },
		{ word: "forhold", hint: "Forbindelse mellom to eller flere ting eller personer." },
		{ word: "situasjon", hint: "Omstendigheter på et bestemt tidspunkt." },
		{ word: "løsning", hint: "Svar på et problem eller vei ut av en vanskelig situasjon." },
		{ word: "beslutning", hint: "Et valg man tar etter å ha tenkt over alternativer." },
		{ word: "aktivitet", hint: "Noe man gjør, spesielt for å være aktiv eller more seg." },
		{ word: "miljø", hint: "Omgivelsene rundt oss, både naturlige og menneskeskapte." },
		{ word: "kultur", hint: "Måten en gruppe mennesker lever, deres tradisjoner og verdier." },
		{ word: "tradisjon", hint: "Skikker og ritualer som går i arv fra generasjon til generasjon." },
		{ word: "generasjon", hint: "En gruppe mennesker født omtrent på samme tid." },
		{ word: "teknologi", hint: "Vitenskapelige metoder og verktøy som gjør livet lettere." },
		{ word: "fremtid", hint: "Tiden som kommer etter nå." },
		{ word: "fortid", hint: "Tiden som har vært før nå." },
	],

	hard: [
		// Advanced level words
		{ word: "bevissthet", hint: "Tilstand av å være klar over noe eller seg selv." },
		{ word: "anerkjennelse", hint: "Når noen får ros eller blir lagt merke til for noe bra." },
		{ word: "forpliktelse", hint: "En avtale eller ansvar man må følge opp." },
		{ word: "forutsigelse", hint: "En antakelse om hva som vil skje i fremtiden." },
		{ word: "hensiktsmessig", hint: "Noe som passer godt til formålet." },
		{ word: "selvrefleksjon", hint: "Å tenke over egne tanker og handlinger." },
		{ word: "bærekraftig", hint: "Noe som varer lenge uten å skade miljøet." },
		{ word: "integritet", hint: "Å være ærlig og handle i tråd med sine verdier." },
		{ word: "dedikasjon", hint: "Å være fullt og helt forpliktet til noe." },
		{ word: "systematisk", hint: "Å gjøre ting på en organisert og planlagt måte." },
		{ word: "konstruktiv", hint: "Noe som bidrar positivt til forbedring." },
		{ word: "analytisk", hint: "Evnen til å bryte ned komplekse problemer." },
		{ word: "strategisk", hint: "Planlegging for å nå langsiktige mål." },
		{ word: "innovativ", hint: "Å innføre nye ideer eller metoder." },
		{ word: "konsistent", hint: "Å være stabil og forutsigbar over tid." },
		{ word: "omfattende", hint: "Noe som inkluderer mange aspekter eller detaljer." },
		{ word: "betydningsfull", hint: "Noe som har stor verdi eller viktighet." },
		{ word: "vesentlig", hint: "Noe som er viktig og nødvendig." },
		{ word: "tilpasset", hint: "Noe som er endret for å passe bedre." },
		{ word: "forhåndsdefinert", hint: "Noe som er bestemt på forhånd." },
		{ word: "tilstrekkelig", hint: "Nok til å dekke behovet." },
		{ word: "anbefaling", hint: "Et forslag om hva som bør gjøres." },
		{ word: "betingelse", hint: "Et krav som må oppfylles." },
		{ word: "dimensjon", hint: "Et aspekt eller side ved noe." },
		{ word: "prosedyre", hint: "En bestemt måte å gjøre noe på." },
		{ word: "metodikk", hint: "Systematisk tilnærming til å løse problemer." },
		{ word: "implementering", hint: "Å sette en plan eller ide ut i praksis." },
		{ word: "optimalisering", hint: "Å gjøre noe så bra som mulig." },
		// Additional hard words
		{ word: "paradigmeskifte", hint: "En fundamental endring i måten å tenke på." },
		{ word: "epistemologi", hint: "Studiet av kunnskap og hvordan vi vet ting." },
		{ word: "fenomenologi", hint: "Studiet av opplevelser og bevissthet." },
		{ word: "eksistensialisme", hint: "Filosofi som fokuserer på individets frihet og ansvar." },
		{ word: "determinisme", hint: "Teorien om at alt er forutbestemt av tidligere årsaker." },
		{ word: "relativisme", hint: "Synet på at sannhet er relativ til kontekst." },
		{ word: "objektivitet", hint: "Å være nøytral og ikke påvirket av personlige følelser." },
		{ word: "subjektivitet", hint: "Å være påvirket av personlige oppfatninger og følelser." },
		{ word: "dialektikk", hint: "Metode for å finne sannhet gjennom diskusjon av motsatte ideer." },
		{ word: "hegemoni", hint: "Dominerende innflytelse eller autoritet over andre." },
		{ word: "ideologi", hint: "Et system av ideer og idealer som former politiske og sosiale handlinger." },
		{ word: "diskurs", hint: "Måten vi snakker om og forstår bestemte emner." },
		{ word: "paradigme", hint: "En etablert modell eller mønster for hvordan ting gjøres." },
		{ word: "metamorfose", hint: "En fullstendig forvandling eller endring i form eller natur." },
		{ word: "ambivalens", hint: "Å ha motstridende følelser eller holdninger til noe." },
		{ word: "kontemporær", hint: "Tilhørende eller eksisterende på samme tid som noe annet." },
		{ word: "autentisitet", hint: "Kvaliteten av å være ekte, original eller sann mot seg selv." },
		{ word: "legitimitet", hint: "Retten til å utøve makt eller autoritet." },
		{ word: "hierarki", hint: "Et system hvor elementer er rangert i nivåer av viktighet." },
		{ word: "byråkrati", hint: "Et system med mange regler og administrative prosedyrer." },
		{ word: "meritokrati", hint: "Et system hvor makt gis til folk basert på deres evner." },
		{ word: "pluralisme", hint: "Aksept for mangfold av meninger og livsstiler." },
		{ word: "empirisme", hint: "Teorien om at kunnskap kommer fra sanseerfaringer." },
		{ word: "pragmatisme", hint: "Tilnærming som fokuserer på praktiske resultater." },
		{ word: "nihilisme", hint: "Troen på at livet mangler objektiv mening eller verdi." },
		{ word: "eksistensielle", hint: "Relatert til eksistens og meningen med livet." },
		{ word: "transsendentale", hint: "Som går utover vanlig erfaring eller kunnskap." },
		{ word: "immanente", hint: "Iboende eller naturlig tilstede i noe." },
		{ word: "essensialistisk", hint: "Basert på troen på at ting har faste, iboende egenskaper." },
	],
};
