export const norwegianWords = [
	{ word: "forståelse", hint: "Evnen til å oppfatte og tolke informasjon." },
	{ word: "utvikling", hint: "En prosess der noe blir bedre eller mer avansert." },
	{ word: "bevissthet", hint: "Tilstand av å være klar over noe eller seg selv." },
	{ word: "selvstendig", hint: "En person som klarer seg uten hjelp fra andre." },
	{ word: "anerkjennelse", hint: "Når noen får ros eller blir lagt merke til for noe bra." },
	{ word: "tilgjengelig", hint: "Noe som er lett å få tak i eller bruke." },
	{ word: "forpliktelse", hint: "En avtale eller ansvar man må følge opp." },
	{ word: "gjennomføre", hint: "Å gjøre ferdig en oppgave eller plan." },
	{ word: "sannsynlighet", hint: "Hvor stor sjanse det er for at noe skjer." },
	{ word: "overbevisende", hint: "Noe som får andre til å tro på det du sier." },
	{ word: "forutsigelse", hint: "En antakelse om hva som vil skje i fremtiden." },
	{ word: "hensiktsmessig", hint: "Noe som passer godt til formålet." },
	{ word: "innflytelse", hint: "Evnen til å påvirke andre eller en situasjon." },
	{ word: "oppmerksomhet", hint: "Når man konsentrerer seg om noe eller noen." },
	{ word: "tilrettelegge", hint: "Å gjøre det lettere for andre å få til noe." },
	{ word: "virkeligheten", hint: "Det som faktisk skjer, ikke fantasi." },
	{ word: "forventninger", hint: "Tanker om hva som kommer til å skje." },
	{ word: "selvrefleksjon", hint: "Å tenke over egne tanker og handlinger." },
	{ word: "utfordringer", hint: "Noe som er vanskelig og krever innsats å løse." },
	{ word: "bærekraftig", hint: "Noe som varer lenge uten å skade miljøet." },
	{ word: "kompetanse", hint: "Kunnskap og ferdigheter innen et område." },
	{ word: "kommunikasjon", hint: "Å utveksle informasjon mellom mennesker." },
	{ word: "samarbeid", hint: "Når flere personer jobber sammen mot et mål." },
	{ word: "kreativitet", hint: "Evnen til å skape noe nytt og originalt." },
	{ word: "inspirasjon", hint: "Følelse som motiverer til handling eller skapelse." },
	{ word: "toleranse", hint: "Å akseptere andres meninger og forskjellighet." },
	{ word: "empati", hint: "Evnen til å forstå andres følelser." },
	{ word: "respekt", hint: "Å vise høflighet og anerkjennelse overfor andre." },
	{ word: "integritet", hint: "Å være ærlig og handle i tråd med sine verdier." },
	{ word: "fleksibilitet", hint: "Evnen til å tilpasse seg endringer." },
	{ word: "engasjement", hint: "Å være interessert og aktiv i noe." },
	{ word: "dedikasjon", hint: "Å være fullt og helt forpliktet til noe." },
	{ word: "systematisk", hint: "Å gjøre ting på en organisert og planlagt måte." },
	{ word: "konstruktiv", hint: "Noe som bidrar positivt til forbedring." },
	{ word: "analytisk", hint: "Evnen til å bryte ned komplekse problemer." },
	{ word: "strategisk", hint: "Planlegging for å nå langsiktige mål." },
	{ word: "effektiv", hint: "Å oppnå gode resultater med minst mulig innsats." },
	{ word: "innovativ", hint: "Å innføre nye ideer eller metoder." },
	{ word: "målrettet", hint: "Å være fokusert på å nå bestemte mål." },
	{ word: "konsistent", hint: "Å være stabil og forutsigbar over tid." },
	{ word: "omfattende", hint: "Noe som inkluderer mange aspekter eller detaljer." },
	{ word: "grunnleggende", hint: "De viktigste og mest essensielle elementene." },
	{ word: "betydningsfull", hint: "Noe som har stor verdi eller viktighet." },
	{ word: "avgjørende", hint: "Noe som har stor innvirkning på utfallet." },
	{ word: "vesentlig", hint: "Noe som er viktig og nødvendig." },
	{ word: "relevant", hint: "Noe som er passende og har sammenheng med emnet." },
	{ word: "tilpasset", hint: "Noe som er endret for å passe bedre." },
	{ word: "forhåndsdefinert", hint: "Noe som er bestemt på forhånd." },
	{ word: "tilstrekkelig", hint: "Nok til å dekke behovet." },
	{ word: "nødvendig", hint: "Noe som må være til stede eller gjøres." },
	{ word: "anbefaling", hint: "Et forslag om hva som bør gjøres." },
	{ word: "betingelse", hint: "Et krav som må oppfylles." },
	{ word: "konsekvens", hint: "Resultatet av en handling eller beslutning." },
	{ word: "sammenheng", hint: "Forbindelse mellom forskjellige elementer." },
	{ word: "perspektiv", hint: "En måte å se på eller forstå noe." },
	{ word: "dimensjon", hint: "Et aspekt eller side ved noe." },
	{ word: "kapasitet", hint: "Maksimal mengde eller evne til å håndtere noe." },
	{ word: "potensial", hint: "Muligheter for fremtidig utvikling eller suksess." },
	{ word: "ressurser", hint: "Tilgjengelige midler eller materialer som kan brukes." },
	{ word: "struktur", hint: "Måten noe er organisert eller bygget opp." },
	{ word: "prosedyre", hint: "En bestemt måte å gjøre noe på." },
	{ word: "metodikk", hint: "Systematisk tilnærming til å løse problemer." },
	{ word: "tilnærming", hint: "En måte å håndtere eller nærme seg noe." },
	{ word: "implementering", hint: "Å sette en plan eller ide ut i praksis." },
	{ word: "evaluering", hint: "Prosessen med å vurdere kvalitet eller verdi." },
	{ word: "optimalisering", hint: "Å gjøre noe så bra som mulig." },
	{ word: "koordinering", hint: "Å organisere forskjellige aktiviteter sammen." },
	{ word: "prioritering", hint: "Å rangere oppgaver etter viktighet." },
	{ word: "planlegging", hint: "Å forberede og organisere fremtidige aktiviteter." },
	{ word: "dokumentasjon", hint: "Skriftlig materiale som beviser eller forklarer noe." },
	{ word: "informasjon", hint: "Data eller kunnskap som er kommunisert." },
];
